### ISSUE TITLE
sidebar menu (small screen) only contains "home" entry

### ISSUE THREAD

**Issue by msharp1** [getgrav/grav-skeleton-onepage-site#9]
Hi,
Is it expected ? I was expecting to see the section entries of the top menu.
Side question : why the choice of a sidebar vs a top menu hamburger ?

**Comment by flaviocopes** [comment]
Yes because that's how the Antimatter theme works, on-page navigation is useless on mobile since you can just scroll, that kind of navigation is expected to point you to subpages of the site.

Don't understand the second question, it _is_ a top-menu hamburger that opens a sidebar when clicked.

![screen shot 2016-03-17 at 19 48 02](https://cloud.githubusercontent.com/assets/11783388/13857246/596fffee-ec79-11e5-822c-fc247d945575.png)

**Comment by msharp1** [comment]
> Yes because that's how the Antimatter theme works, on-page navigation is useless on mobile since you can just scroll, that kind of navigation is expected to point you to subpages of the site.

Understood, thanks

> it is a top-menu hamburger that opens a sidebar when clicked.

Well :) You're right, what I meant is the top right hamburger icon opens - on clic - a sidebar menu, not a top drop down menu. So my question was, why a sidebar menu VS a top drop down menu ?

**Comment by flaviocopes** [comment]
I didn't build the theme, and I'm not a UI/UX expert, but it's a rather common behaviour from what I see around the web.

**Comment by msharp1** [comment]
Anyway I'm out of topic because it's more related to https://github.com/getgrav/grav-theme-antimatter/issues. I'll ask there because as far as I can see, most current grav's skeleton demo display a top drop-down menu on small devices rather than a sidebar. You can close that one, thanks @flaviocopes .
